/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package designpatterns;

import org.checkerframework.checker.units.qual.m;

import designpatterns.strategypattern.Duck;
import designpatterns.strategypattern.MallardDuck;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        
        Duck mallard = new MallardDuck();
        mallard.performQuack();
        mallard.perfomFly();
]
    }
}
